# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.TextField(max_length=200)),
                ('link', models.TextField(max_length=200)),
            ],
        ),
    ]
